services:

  vmagent:
    image: victoriametrics/vmagent:v1.79.0
    restart: unless-stopped
    container_name: metrics_vmagent
    command:
      - "-promscrape.config=/config/vmagent-prom.yml"
      - "-promscrape.config.strictParse"
      - "-remoteWrite.url=${PROMETHEUS_URL}"
      - "-remoteWrite.tmpDataPath=/vmagent-remotewrite-data"
      - "-remoteWrite.basicAuth.username=${PROMETHEUS_USER}"
      - "-remoteWrite.basicAuth.password=${PROMETHEUS_PASSWORD}"
      - "-promscrape.suppressScrapeErrors=false"
    volumes:
      - ./vmagent-prom.yml:/config/vmagent-prom.yml
      - vmagent-buffer:/vmagent-remotewrite-data
    networks:
      - default
      - reverse-proxy-traefik
    expose:
      - 8429
    labels:
      org.label-schema.group: "monitoring"

  node-exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
      - 8080
    labels:
      org.label-schema.group: "monitoring"

  portainer:
    image: portainer/agent:2.14.1-alpine
    container_name: portainer_edge_agent
    environment:
      - EDGE=${PORTAINER_EDGE}
      - EDGE_ID=${PORTAINER_EDGE_ID}
      - EDGE_KEY=${PORTAINER_EDGE_KEY}
      - EDGE_INSECURE_POLL=${PORTAINER_EDGE_INSECURE_POLL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

networks:
  reverse-proxy-traefik:
    external: true

volumes:
  vmagent-buffer:
  portainer_agent_data:
