version: "3.1"
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=laravel
    expose:
      - "3306"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:5.1 #-fpm-alpine
    restart: on-failure
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=my-secret-pw
    ports:
      - 8001:80
    networks:
      - backend
    depends_on:
      - mysql

  server:
    build: ./
    image: flf_server
    restart: on-failure
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:yhlA8bbReEexkxGzKFpgy0Zmuq+zRPI1rYmpr2HWtPc=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      # Log
      - LOG_CHANNEL=stack
      # DB
      - DB_CONNECTION=mysql
#      - DATABASE_URL=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw
      # Misc
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      # Redis
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      # Mail
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=null
      - MAIL_FROM_NAME="${APP_NAME}"
      # AWS
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      # Pusher
      - PUSHER_APP_ID=
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - PUSHER_APP_CLUSTER=mt1
      # Mix
      - MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
      - MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
    ports:
      - "8000:80"
#    volumes:
#      - apk-volume:/dist:Z
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
