services:
  reverse-proxy:
    image: traefik:v2.7
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      # Provider
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=reverse-proxy-traefik"
      # Entrypoints
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # HTTP
    labels:
      - "traefik.enable=true"
      # [Routing]
      - "traefik.http.routers.reverse-proxy.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.reverse-proxy.service=api@internal"
      # [Midleware]
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}"
      - "traefik.http.routers.reverse-proxy.middlewares=traefik-auth@docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Traefik listen Docker events
    networks:
      - proxynet

networks:
  proxynet:
    name: reverse-proxy-traefik
    driver: bridge
