version: '3.8'

services:
  postgres:
    container_name: postgres_container2
    image: postgres
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped 

  api: 
    build:
      context: ./
      args:
        DATABASE_URL: $DATABASE_URL # ecto://postgres:postgres@postgres/table_prod
        SECRET_KEY_BASE: $SECRET_KEY_BASE
    environment:
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_URL: $PG_URL
      DATABASE_URL: $DATABASE_URL
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    ports:
      - "4000:4000"
    depends_on: 
      - postgres

volumes:
    postgres: